theme: null
markdown: kramdown
sass:
  style: compressed
title: "azurepwq"
description: "Azure Pan(azurepwq | azurepwq@gmail.com) - [Software Engineer | Writer | INFP] passionate about deep learning, AI security, and blockchain technology"
repository: "azurepwq/azurepwq"
github: [metadata]